### PR TITLE
created second largest element in an array program 

### PR DESCRIPTION
**Pull request by avishka45**
created second largest element in an array program, 
solves issue #48 

pls review and let me know

### CODE REVIEW

**Comment by Ayushgupta0207** [comment]
I reviewed it and found it apt to merge. I am merging the PR

**Comment by avishka45** [comment]
thanks @Ayushgupta0207

**Comment by avishka45** [comment]
@Ayushgupta0207 provide the hacktober fest accepted label

**Comment by Ayushgupta0207** [comment]
It is already on this repository

**Pull request merged**
