### PR TITLE
made python programs directory and added first code of palindrome detection

### PR DESCRIPTION
**Pull request by Jash7447**

### CODE REVIEW

**Comment by Jash7447** [comment]
please add this as a hacktoberfest submission.

**Comment by Ayushgupta0207** [comment]
I have added already

**Comment by Jash7447** [comment]
so I'm not sure, why is it not showing in my hacktober progress? I mean it still shows 0/4.

**Comment by Ayushgupta0207** [comment]
I think the previous year there was a timer of about 7 days to verify a pr and may be this year also there should be a same rule

**Pull request merged**
